FROM ubuntu:latest

WORKDIR /test
COPY example.txt .
RUN cat example.txt

# COPY a directory (ignoring .dockerignore) to a directory, COPY a file to a file, COPY a file to a directory
# Switch to relative WORKDIR, absolute WORKDIR
# Use an ENV
# RUN a command or two
